apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restaurantlisting
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:betorosas/gitOps.git
    targetRevision: main
    path: k8s   # <-- CAMBIA esto si tus manifests estÃ¡n en una carpeta (ej: k8s/restaurant)

  destination:
    server: https://kubernetes.default.svc
    namespace: restaurant  # <-- CAMBIA esto si usas otro namespace (ej: restaurant)

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   
      - Validate=true      